authors:
  bugo:
    name: Bugo
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/229402
    url: /about/
  digger:
    name: digger
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/1187218?v=4
    url: https://github.com/realdigger
  suki:
    name: All Colours Sam (MissAllSunday)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/3420756?v=4
    url: https://github.com/MissAllSunday
  diego:
    name: Diego Andrés Cortés
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/3318127?v=4
    url: https://github.com/DiegoAndresCortes
  shawnb61:
    name: shawnb61 (sbulen)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/23568484?v=4
    url: https://github.com/sbulen
  sycho:
    name: Sami Mazouz (SychO9)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/20267363?v=4
    url: https://github.com/SychO9
  sleepy:
    name: SleePy (jdarwood007)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/732116?v=4
    url: https://github.com/jdarwood007
  live627:
    name: John Rayes (live627)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/431799?v=4
    url: https://github.com/live627
  spuds:
    name: Spuds
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/1181042?v=4
    url: https://github.com/Spuds
  sesq:
    name: Jon Stovell (Sesquipedalian)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/191731?v=4
    url: https://github.com/Sesquipedalian
  rjen:
    name: Bopske (@rjen)
    description: Автор мода
    avatar: https://avatars.githubusercontent.com/u/24902644?v=4
    url: https://github.com/Bopske
